// const DEFAULT_PROVIDER_PLACEHOLDER = "Allocate To Service Provider";
// const DEFAULT_RECIPIENT_PLACEHOLDER = "Select recipients or type to search...";
// const GRAPHQL_ENDPOINT = "https://peterpm.vitalstats.app/api/v1/graphql";
// const GRAPHQL_WS_ENDPOINT = "wss://peterpm.vitalstats.app/api/v1/graphql";
// const GRAPHQL_API_KEY = "1rBR-jpR3yE3HE1VhFD0j";
// const INQUIRY_RECORD_ID = "312"; 
// const CONTACT_ID = "168"; //Primary Contact of inquiry
// const COMPANY_ID = "63"; //Company linked to inquiry
// const JOB_ID = "375"; // Job linked to inquiry
// const PROPERTY_ID = "174"; // Property linked to inquiry
// const JOB_UNIQUE_ID = "62GF7PS"; // Unique Job ID linked to inquiry
// const UPLOAD_ENDPOINT = "https://peterpm.vitalstats.app/api/v1/rest/upload";
// const accountType = "Company";
